version: '3.9'

services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.build
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./database:/data/db
